# ============================================================================
# UR10 Robot Kiosk - Docker Compose Configuration
# ============================================================================
# Complete containerized deployment for the UR10 robot kiosk system
# Includes robot server, kiosk UI, nginx proxy, and supporting services
# ============================================================================

version: '3.8'

services:
  # UR10 Robot Server (FastAPI)
  robot-server:
    build:
      context: .
      dockerfile: deployment/docker/robot-server/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
    container_name: ur10-robot-server
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ROBOT_IP=${ROBOT_IP:-192.168.1.100}
      - ROBOT_PORT=${ROBOT_PORT:-30002}
      - MOCK_MODE=${MOCK_MODE:-false}
      - CORS_ORIGINS=https://localhost,https://kiosk-ui
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./ur10_kiosk.db}
    volumes:
      - robot-data:/app/data
      - robot-logs:/app/logs
      - ./deployment/security/certificates:/app/certs:ro
    networks:
      - ur10-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Redis dependency removed - sessions are stored in-memory
    # Traefik labels removed - reverse proxy not used in development

  # Kiosk UI (React PWA with Nginx)
  kiosk-ui:
    build:
      context: .
      dockerfile: deployment/docker/kiosk-ui/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-1.0.0}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://localhost:8000}
        VITE_WS_URL: ${VITE_WS_URL:-wss://localhost:8000}
    container_name: ur10-kiosk-ui
    restart: unless-stopped
    ports:
      - "${KIOSK_HTTP_PORT:-80}:80"
      - "${KIOSK_HTTPS_PORT:-443}:443"
    volumes:
      - ./deployment/security/certificates:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    networks:
      - ur10-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - robot-server
    # Traefik labels removed - reverse proxy not used in development

  # Redis service removed - sessions are stored in-memory, not in Redis

  # PostgreSQL service removed - no database needed (all data is in-memory)

  # Production services removed for development simplicity:
  # - Traefik reverse proxy (not needed for dev)
  # - Prometheus monitoring (overkill for dev) 
  # - Grafana dashboards (overkill for dev)

# Networks
networks:
  ur10-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes
volumes:
  # Volumes for active services
  robot-data:
    driver: local
  robot-logs:
    driver: local
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local
  
  # Removed unused volumes:
  # redis-data (Redis service removed)
  # postgres-data (PostgreSQL service removed)
  # traefik-data (Traefik service removed)
  # prometheus-data (Prometheus service removed)
  # grafana-data (Grafana service removed)

